#!/usr/bin/env bash
#MISE description="Copy CHANGELOG.md and THIRD_PARTY_LICENSES.md into docs/ for the site build"
#MISE hide=true
set -euo pipefail

cp CHANGELOG.md docs/changelog.md
cp THIRD_PARTY_LICENSES.md docs/third-party-licenses.md
